[package]
name = "cdhydro"
version = "0.1.0"
authors = ["Ryan WS <jwestern@uoguelph.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.1"
